-- gemote Config

-- Keybind to spam
key = "MOUSE3"
-- File to output to
outfile = "autoexec.cfg"
-- Only allow emotes with a sound or saying that contains the filter.
-- For example to only get barney emotes a good filter would be "ba_".
filter = ""
-- Shuffle the results?
shuffle = true

AddEmote("drink a big bucket of shit", "speach/obeyyourthirstsync.ogg", true)
AddEmote("drink a big bucket of horse dick", "speach/obeyyourthirst2.ogg", true)
AddEmote("lag!", "speach/lag2.ogg", true)
AddEmote("laff", {"speach/laff1.ogg", "speach/laff2.ogg", "speach/laff3.ogg", "speach/laff4.ogg", "speach/laff5.ogg"}, true)
AddEmote("enough of your mumbo jumbo", "vo/npc/male01/vanswer01.wav", true)
AddEmote("bullshit", "vo/npc/male01/question26.wav")
AddEmote("yay", "vo/npc/Barney/ba_yell.wav")
AddEmote("shit", "vo/npc/Barney/ba_ohshit03.wav")
AddEmote("about that bear i owed ya", "vo/trainyard/ba_thatbeer02.wav", true)
AddEmote("enough of your bullshit", "vo/NovaProspekt/al_enoughbs01.wav", true)
AddEmote("hax", "vo/npc/male01/hacks01.wav", true)
AddEmote("hacks", "vo/npc/male01/hacks02.wav", true)
AddEmote("h4x", "vo/npc/male01/thehacks01.wav", true)
AddEmote("h4cks", "vo/npc/male01/thehacks02.wav", true)
AddEmote("okay", {"vo/npc/male01/ok01.wav", "vo/npc/male01/ok02.wav"})
AddEmote("derka", {"vo/npc/vortigaunt/vortigese12.wav", "vo/npc/vortigaunt/vortigese11.wav"}, true)
AddEmote("noes", "vo/npc/Alyx/ohno_startle01.wav", true)
AddEmote("get down", {"vo/npc/Barney/ba_getdown.wav", "vo/npc/male01/getdown02.wav"})
AddEmote("gtfo", "vo/npc/male01/gethellout.wav")
AddEmote("gtho", "vo/npc/male01/gethellout.wav")
AddEmote("yeah", "vo/npc/male01/yeah02.wav")
AddEmote("rofl", "vo/Citadel/br_laugh01.wav")
AddEmote("lmao", "vo/Citadel/br_laugh01.wav")
AddEmote("run", "vo/npc/male01/strider_run.wav")
AddEmote("run for your life", {"vo/npc/male01/runforyourlife01.wav", "vo/npc/male01/runforyourlife02.wav", "vo/npc/male01/runforyourlife03.wav"})
AddEmote("fantastic", {"vo/npc/male01/fantastic01.wav", "vo/npc/male01/fantastic02.wav"})
AddEmote("headcrabs", {"vo/npc/male01/headcrabs01.wav", "vo/npc/male01/headcrabs02.wav"})
AddEmote("headhumpers", "vo/npc/Barney/ba_headhumpers.wav", true)
AddEmote("hello", "vo/coast/odessa/nlo_cub_hello.wav")
AddEmote("eek", "ambient/voices/f_scream1.wav", true)
AddEmote("uh oh", "vo/npc/male01/uhoh.wav")
AddEmote("sodomy!", {"vo/ravenholm/madlaugh01.wav", "vo/ravenholm/madlaugh02.wav", "vo/ravenholm/madlaugh03.wav", "vo/ravenholm/madlaugh04.wav"}, true)
AddEmote("oops", "vo/npc/male01/whoops01.wav", true)
AddEmote("shut up", "vo/npc/male01/answer17.wav")
AddEmote("shutup", "vo/npc/male01/answer17.wav")
AddEmote("right on", "vo/npc/male01/answer32.wav", true)
AddEmote("help", "vo/npc/male01/help01.wav")
AddEmote("haxz", "vo/npc/male01/herecomehacks01.wav", true)
AddEmote("hi", {"vo/npc/male01/hi01.wav", "vo/npc/male01/hi02.wav"})
AddEmote("let's go", {"vo/npc/male01/letsgo01.wav", "vo/npc/male01/letsgo02.wav"})
AddEmote("lets go", {"vo/npc/male01/letsgo01.wav", "vo/npc/male01/letsgo02.wav"})
AddEmote("moan", {"vo/npc/male01/moan01.wav", "vo/npc/male01/moan02.wav", "vo/npc/male01/moan03.wav", "vo/npc/male01/moan04.wav", "vo/npc/male01/moan05.wav"}, true)
AddEmote("nice", "vo/npc/male01/nice.wav")
AddEmote("noo", {"vo/npc/Barney/ba_no01.wav", "vo/npc/Barney/ba_no02.wav"}, true)
AddEmote("nooo", "vo/npc/male01/no02.wav", true)
AddEmote("oh no", "vo/npc/male01/ohno.wav", "vo/npc/male01/gordead_ans05.wav")
AddEmote("joygasm", "vo/npc/female01/pain06.wav", true)
AddEmote("zombies", {"vo/npc/male01/zombies01.wav", "vo/npc/male01/zombies02.wav"}, true)
AddEmote("da man", "bot/whos_the_man.wav", true)
AddEmote("my house", "bot/this_is_my_house.wav", true)
AddEmote("party", "bot/its_a_party.wav", true)
AddEmote("watch out", "vo/npc/male01/watchout.wav")
AddEmote("excuse me", {"vo/npc/male01/excuseme01.wav", "vo/npc/male01/excuseme02.wav"})
AddEmote("you sure about that?", "vo/npc/male01/answer37.wav", true)
AddEmote("groan", "vo/npc/male01/moan04.wav", true)
AddEmote("gasp", {"vo/npc/male01/startle01.wav", "vo/npc/male01/startle02.wav"}, true)
AddEmote("sorry", {"vo/npc/male01/sorry01.wav", "vo/npc/male01/sorry02.wav", "vo/npc/male01/sorry03.wav"})
AddEmote("welcome to city 17", {"vo/Breencast/br_welcome01.wav", "vo/Breencast/br_welcome06.wav"}, true)
AddEmote("it's safer here", "vo/Breencast/br_welcome07.wav", true)
AddEmote("i'm talking to you", "vo/Breencast/br_tofreeman02.wav", true)
AddEmote("serve mankind", "vo/Breencast/br_tofreeman12.wav", true)
AddEmote("get going", {"vo/canals/shanty_go_nag03.wav", "vo/trainyard/cit_blocker_go01.wav", "vo/trainyard/cit_blocker_go03.wav"})
AddEmote("go on out", "vo/canals/gunboat_goonout.wav", true)
AddEmote("get outta here", {"vo/canals/shanty_go_nag01.wav", "vo/canals/boxcar_go_nag03.wav"})
AddEmote("go on", {"vo/canals/shanty_go_nag02.wav", "vo/trainyard/cit_blocker_go02.wav"})
AddEmote("hey", "vo/canals/shanty_hey.wav")
AddEmote("get in here hurry", "vo/canals/matt_getin.wav", true)
AddEmote("hit the road jack", "vo/canals/boxcar_go_nag04.wav", true)
AddEmote("no", "vo/Citadel/eli_notobreen.wav")
AddEmote("no!", "vo/Citadel/br_failing11.wav", true)
AddEmote("never", "vo/Citadel/eli_nonever.wav")
AddEmote("you fool", "vo/Citadel/br_youfool.wav", true)
AddEmote("good god", "vo/Citadel/eli_goodgod.wav")
AddEmote("cheer", {"vo/coast/odessa/male01/nlo_cheer01.wav", "vo/coast/odessa/male01/nlo_cheer02.wav", "vo/coast/odessa/male01/nlo_cheer03.wav", "vo/coast/odessa/male01/nlo_cheer04.wav"}, true)
AddEmote("drive safely", "vo/coast/odessa/male01/nlo_citizen_drivesafe.wav", true)
AddEmote("whoops", "vo/k_lab/ba_whoops.wav", true)
AddEmote("gee thanks", "vo/k_lab/ba_geethanks.wav", true)
AddEmote("what the hell", "vo/k_lab/ba_whatthehell.wav")
AddEmote("it's your pet the freakin headhumper", "vo/k_lab/ba_headhumper01.wav", true)
AddEmote("i'll stay here", "vo/npc/male01/illstayhere01.wav")
AddEmote("i'm sticking here", "vo/npc/male01/imstickinghere01.wav", true)
AddEmote("up there", {"vo/npc/male01/upthere01.wav", "vo/npc/male01/upthere02.wav"})
AddEmote("lead the way", {"vo/npc/male01/leadtheway02.wav", "vo/npc/male01/leadtheway01.wav"}, true)
AddEmote("over there", {"vo/npc/male01/overthere01.wav", "vo/npc/male01/overthere02.wav"})
AddEmote("ok i'm ready", {"vo/npc/male01/okimready01.wav", "vo/npc/male01/okimready02.wav", "vo/npc/male01/okimready03.wav"})
AddEmote("i'm with you", "vo/npc/male01/answer13.wav", true)
AddEmote("hey over here", "vo/npc/male01/overhere01.wav", true)
AddEmote("behind you", {"vo/npc/male01/behindyou01.wav", "vo/npc/male01/behindyou02.wav"})
AddEmote("follow me", "vo/npc/male01/squad_away03.wav")
AddEmote("pardon me", {"vo/npc/male01/pardonme01.wav", "vo/npc/male01/pardonme02.wav"})
AddEmote("got one", {"vo/npc/male01/gotone01.wav", "vo/npc/male01/gotone02.wav"}, true)
AddEmote("finally", "vo/npc/male01/finally.wav")
AddEmote("wait for me", "vo/npc/male01/squad_reinforce_single04.wav")
AddEmote("take cover", "vo/npc/male01/takecover02.wav")
AddEmote("that's a manhack", "vo/npc/male01/itsamanhack01.wav", true)
AddEmote("it's a manhack", "vo/npc/male01/itsamanhack02.wav", true)
AddEmote("incoming", "vo/npc/male01/incoming02.wav")
AddEmote("ready when you are", {"vo/npc/male01/readywhenyouare01.wav", "vo/npc/male01/readywhenyouare02.wav"}, true)
AddEmote("don't forget hawaii", "vo/npc/male01/answer34.wav", true)
AddEmote("that's enough outta you", "vo/npc/male01/answer39.wav", true)
AddEmote("wait for us", "vo/npc/male01/squad_reinforce_group04.wav")
AddEmote("we trusted you", {"vo/npc/male01/wetrustedyou01.wav", "vo/npc/male01/wetrustedyou02.wav"}, true)
AddEmote("god i'm hungry", "vo/npc/male01/question28.wav", true)
AddEmote("you're talking to yourself again", "vo/npc/male01/answer09.wav", true)
AddEmote("come on everybody", "vo/npc/male01/squad_follow02.wav", true)
AddEmote("watch what you're doing", "vo/npc/male01/watchwhat.wav", true)
AddEmote("your mind is in the gutter", "vo/npc/male01/answer20.wav", true)
AddEmote("here they come!", "vo/npc/male01/heretheycome01.wav", true)
AddEmote("same here", "vo/npc/male01/answer07.wav")
AddEmote("i wouldn't say that too loud", "vo/npc/male01/answer10.wav", true)
AddEmote("i'll put it on your tombstone", "vo/npc/male01/answer11.wav", true)
AddEmote("have you ever had an original thought?", "vo/npc/male01/answer16.wav", true)
AddEmote("let's concentrate on the task at hand", "vo/npc/male01/answer18.wav", true)
AddEmote("keep your mind on your work", "vo/npc/male01/answer19.wav", true)
AddEmote("you never know", "vo/npc/male01/answer22.wav", true)
AddEmote("you never can tell", "vo/npc/male01/answer23.wav", true)
AddEmote("why are you telling me?", "vo/npc/male01/answer24.wav", true)
AddEmote("how about that", "vo/npc/male01/answer25.wav", true)
AddEmote("want a bet?", "vo/npc/male01/answer27.wav")
AddEmote("what am i supposed to do about it?", "vo/npc/male01/answer29.wav")
AddEmote("you talking to me?", "vo/npc/male01/answer30.wav")
AddEmote("leave it alone", "vo/npc/male01/answer38.wav", true)
AddEmote("can't you see i'm busy?", "vo/npc/male01/busy02.wav", true)
AddEmote("look out below", "vo/npc/male01/cit_dropper04.wav", true)
AddEmote("shouldn't we be doing something?", "vo/npc/male01/doingsomething.wav", true)
AddEmote("let's even the odds a little", "vo/npc/male01/evenodds.wav", true)
AddEmote("hold down this spot", {"vo/npc/male01/holddownspot01.wav", "vo/npc/male01/holddownspot02.wav"}, true)
AddEmote("i'm hurt", {"vo/npc/male01/imhurt01.wav", "vo/npc/male01/imhurt02.wav"}, true)
AddEmote("im hurt", {"vo/npc/male01/imhurt01.wav", "vo/npc/male01/imhurt02.wav"}, true)
AddEmote("sometimes i dream about cheese", "vo/npc/male01/question06.wav", true)
AddEmote("i can't remember the last time i had a shower", "vo/npc/male01/question19.wav", true)
AddEmote("watch what you're doing", "vo/npc/male01/watchwhat.wav", true)
AddEmote("you got it", "vo/npc/male01/yougotit02.wav")
AddEmote("we thought you were here to help", {"vo/npc/male01/heretohelp01.wav", "vo/npc/male01/heretohelp02.wav"}, true)
AddEmote("hey doc", {"vo/npc/male01/heydoc01.wav", "vo/npc/male01/heydoc02.wav"}, true)
AddEmote("hit in the gut", {"vo/npc/male01/hitingut01.wav", "vo/npc/male01/hitingut02.wav"}, true)
AddEmote("like that?", "vo/npc/male01/likethat.wav", true)
AddEmote("my leg", {"vo/npc/male01/myleg01.wav", "vo/npc/male01/myleg02.wav"}, true)
AddEmote("my gut", "vo/npc/male01/mygut02.wav", true)
AddEmote("my arm", {"vo/npc/male01/myarm01.wav", "vo/npc/male01/myarm02.wav"}, true)
AddEmote("no no", "vo/npc/male01/no01.wav")
AddEmote("you're not the man i thought you were", {"vo/npc/male01/notthemanithought01.wav", "vo/npc/male01/notthemanithought02.wav"}, true)
AddEmote("one for me and one for me", "vo/npc/male01/oneforme.wav", true)
AddEmote("let me get out of your way", "vo/npc/male01/outofyourway02.wav", true)
AddEmote("i don't think this war is ever going to end", "vo/npc/male01/question01.wav", true)
AddEmote("to think all i used to want to do is sell insurance", "vo/npc/male01/question02.wav", true)
AddEmote("i don't dream anymore", "vo/npc/male01/question03.wav", true)
AddEmote("when this is all over ah who am i kidding", "vo/npc/male01/question04.wav", true)
AddEmote("woah deja vu", "vo/npc/male01/question05.wav", true)
AddEmote("you smell that? it's freedom", "vo/npc/male01/question07.wav", true)
AddEmote("if i ever get my hands on dr. breen", "vo/npc/male01/question08.wav", true)
AddEmote("i could eat a horse hooves and all", "vo/npc/male01/question09.wav", true)
AddEmote("i can't believe this day has finally come", "vo/npc/male01/question10.wav", true)
AddEmote("i'm pretty sure this isn't part of the plan", "vo/npc/male01/question11.wav", true)
AddEmote("looks to me like things are getting worse not better", "vo/npc/male01/question12.wav", true)
AddEmote("if i could live my life over again", "vo/npc/male01/question13.wav", true)
AddEmote("i'm not even gonna tell you what that reminds me of", "vo/npc/male01/question14.wav", true)
AddEmote("they're never gonna make a stalker outta me", "vo/npc/male01/question15.wav", true)
AddEmote("finally change is in the air", "vo/npc/male01/question16.wav", true)
AddEmote("you feel it? i feel it", "vo/npc/male01/question17.wav", true)
AddEmote("i don't feel anything anymore", "vo/npc/male01/question18.wav", true)
AddEmote("some day this will all be a bad memory", "vo/npc/male01/question20.wav", true)
AddEmote("i'm not a betting man but the odds are not good", "vo/npc/male01/question21.wav", true)
AddEmote("doesn't anyone care what i think?", "vo/npc/male01/question22.wav", true)
AddEmote("i can't get this tune outta my head", "vo/npc/male01/question23.wav", true)
AddEmote("i just knew it was gonna be one of those days", "vo/npc/male01/question25.wav", true)
AddEmote("i think i ate something bad", "vo/npc/male01/question27.wav", true)
AddEmote("when this is all over i'm gonna mate", "vo/npc/male01/question29.wav", true)
AddEmote("i'm glad there's no kids around to see this", "vo/npc/male01/question30.wav", true)
AddEmote("scanners", {"vo/npc/male01/scanners01.wav", "vo/npc/male01/scanners02.wav"}, true)
AddEmote("whatever you say", "vo/npc/male01/squad_affirm03.wav")
AddEmote("ok i'm going", "vo/npc/male01/squad_affirm04.wav", true)
AddEmote("here it goes", "vo/npc/male01/squad_affirm05.wav", true)
AddEmote("here goes nothing", "vo/npc/male01/squad_affirm06.wav", true)
AddEmote("here we come", "vo/npc/male01/squad_approach02.wav", true)
AddEmote("on our way", "vo/npc/male01/squad_approach03.wav", true)
AddEmote("coming", "vo/npc/male01/squad_approach04.wav")
AddEmote("this way gang", "vo/npc/male01/squad_away01.wav", true)
AddEmote("over here", "vo/npc/male01/squad_away02.wav")
AddEmote("let's get moving", "npc/male01/squad_follow03.wav")
AddEmote("gordon freeman, you're here", "vo/npc/male01/squad_greet01.wav", true)
AddEmote("stop it freeman", "vo/npc/male01/stopitfm.wav", true)
AddEmote("strider", "vo/npc/male01/strider.wav", true)
AddEmote("this'll do nicely", "vo/npc/male01/thislldonicely01.wav", true)
AddEmote("damn vorts", "vo/npc/male01/vanswer02.wav", true)
AddEmote("i'm not sure how to take that", "vo/npc/male01/vanswer03.wav", true)
AddEmote("should i take that personally?", "vo/npc/male01/vanswer04.wav", true)
AddEmote("speak english", "vo/npc/male01/vanswer05.wav", true)
AddEmote("you got that from me", "vo/npc/male01/vanswer06.wav", true)
AddEmote("that's why we put up with you", "vo/npc/male01/vanswer07.wav", true)
AddEmote("couldn't have put it better myself", "vo/npc/male01/vanswer08.wav", true)
AddEmote("that almost made sense", "vo/npc/male01/vanswer09.wav", true)
AddEmote("something must be wrong with me i almost understood that", "vo/npc/male01/vanswer10.wav", true)
AddEmote("i guess i'm getting used to you vorts", "vo/npc/male01/vanswer11.wav", true)
AddEmote("none of your vort philosophy", "vo/npc/male01/vanswer12.wav", true)
AddEmote("stop you're killing me", "vo/npc/male01/vanswer13.wav", true)
AddEmote("what did i do to deserve this?", "vo/npc/male01/vanswer14.wav", true)
AddEmote("stop looking at me like that", "vo/npc/male01/vquestion01.wav", true)
AddEmote("some things i just never get used to", "vo/npc/male01/vquestion02.wav", true)
AddEmote("i don't know how you things survived as long as you have", "vo/npc/male01/vquestion03.wav", true)
AddEmote("sometimes i wonder how i ended up with you", "vo/npc/male01/vquestion04.wav", true)
AddEmote("you're alright vorty", "vo/npc/male01/vquestion05.wav", true)
AddEmote("you vorts aren't half bad", "vo/npc/male01/vquestion06.wav", true)
AddEmote("if anyone ever told me i'd be pals with a vortigaunt", "vo/npc/male01/vquestion07.wav", true)
AddEmote("you waiting for somebody?", "vo/npc/male01/waitingsomebody.wav", true)
AddEmote("woops", "vo/npc/male01/whoops01.wav", true)
AddEmote("you'd better reload", "vo/npc/male01/youdbetterreload01.wav", true)
AddEmote("bring it on", "vo/npc/Barney/ba_bringiton.wav", true)
AddEmote("damnit", "vo/npc/Barney/ba_damnit.wav")
AddEmote("i don't like the looks of this", "vo/npc/Barney/ba_danger02.wav", true)
AddEmote("down you go", "vo/npc/Barney/ba_downyougo.wav", true)
AddEmote("duck", "vo/npc/Barney/ba_duck.wav")
AddEmote("come on", "vo/npc/Barney/ba_followme02.wav")
AddEmote("get away from there", "vo/npc/Barney/ba_getaway.wav")
AddEmote("get outta the way", "vo/npc/Barney/ba_getoutofway.wav")
AddEmote("you're going down", "vo/npc/Barney/ba_goingdown.wav", true)
AddEmote("grenade", {"vo/npc/Barney/ba_grenade01.wav", "vo/npc/Barney/ba_grenade02.wav"}, true)
AddEmote("here it comes!", "vo/npc/Barney/ba_hereitcomes.wav", true)
AddEmote("hurry up", "vo/npc/Barney/ba_hurryup.wav")
AddEmote("i'm with you buddy", "vo/npc/Barney/ba_imwithyou.wav", true)
AddEmote("maniacal!", {"vo/npc/Barney/ba_laugh01.wav", "vo/npc/Barney/ba_laugh02.wav", "vo/npc/Barney/ba_laugh04.wav"}, true)
AddEmote("yeaheheah", "vo/npc/Barney/ba_laugh03.wav", true)
AddEmote("let's do it", "vo/npc/Barney/ba_letsdoit.wav", true)
AddEmote("look out!", "vo/npc/Barney/ba_lookout.wav", true)
AddEmote("i haven't lost my touch", "vo/npc/Barney/ba_losttouch.wav", true)
AddEmote("ohoh yeah", "vo/npc/Barney/ba_ohyeah.wav", true)
AddEmote("soldiers!", "vo/npc/Barney/ba_soldiers.wav", true)
AddEmote("turret!", "vo/npc/Barney/ba_turret.wav", true)
AddEmote("uh oh here they come", "vo/npc/Barney/ba_uhohheretheycome.wav", true)
AddEmote("i need to get patched up", "vo/npc/Barney/ba_wounded02.wav", true)
AddEmote("i'm hurt pretty bad", "vo/npc/Barney/ba_wounded03.wav", true)
AddEmote("i know you will", "vo/NovaProspekt/eli_iknow.wav", true)
AddEmote("nevermind me save yourselves", "vo/NovaProspekt/eli_nevermindme01.wav", true)
AddEmote("i'll see you there baby", "vo/NovaProspekt/eli_notime01.wav", true)
AddEmote("so this is the combine portal it's smaller than i imagined", "vo/NovaProspekt/eli_thisisportal.wav", true)
AddEmote("but where will you go?", "vo/NovaProspekt/eli_wherewillyougo01.wav", true)
AddEmote("instinct1", "vo/Breencast/br_instinct01.wav", true)
AddEmote("instinct2", "vo/Breencast/br_instinct03.wav", true)
AddEmote("instinct3", "vo/Breencast/br_instinct08.wav", true)
AddEmote("instinct4", "vo/Breencast/br_instinct09.wav", true)
AddEmote("instinct5", "vo/Breencast/br_instinct12.wav", true)
AddEmote("instinct6", "vo/Breencast/br_instinct14.wav", true)
AddEmote("instinct7", "vo/Breencast/br_instinct15.wav", true)
AddEmote("instinct8", "vo/Breencast/br_instinct16.wav", true)
AddEmote("instinct9", "vo/Breencast/br_instinct17.wav", true)
AddEmote("instinct10", "vo/Breencast/br_instinct18.wav", true)
AddEmote("instinct11", "vo/Breencast/br_instinct19.wav", true)
AddEmote("instinct12", "vo/Breencast/br_instinct20.wav", true)
AddEmote("instinct13", "vo/Breencast/br_instinct21.wav", true)
AddEmote("instinct14", "vo/Breencast/br_instinct22.wav", true)
AddEmote("instinct15", "vo/Breencast/br_instinct23.wav", true)
AddEmote("instinct16", "vo/Breencast/br_instinct25.wav", true)
AddEmote("you have plunged humanity in to free fall", "vo/Breencast/br_tofreeman06.wav", true)
AddEmote("even if you offered your surrunder now", "vo/Breencast/br_tofreeman07.wav", true)
AddEmote("help ensure that humanity's trust in you is not misguided", "vo/Breencast/br_tofreeman10.wav", true)
AddEmote("they're shelling us", "vo/canals/male01/stn6_shellingus.wav", true)
AddEmote("incoming!", "vo/canals/male01/stn6_incoming.wav", true)
AddEmote("you can park the boat it'll be safe here", "vo/canals/male01/gunboat_parkboat.wav", true)
AddEmote("let's get a move on we gotta move out before they target us", "vo/canals/male01/gunboat_moveon.wav", true)
AddEmote("you made it just in time we gotta clear outta here before we're discovered", "vo/canals/male01/gunboat_justintime.wav", true)
AddEmote("we'd better hurry we gotta tear down this camp and get outta here", "vo/canals/male01/gunboat_hurry.wav", true)
AddEmote("be careful now", "vo/canals/boxcar_becareful.wav", true)
AddEmote("we really can't afford to get noticed", "vo/canals/boxcar_becareful_b.wav", true)
AddEmote("better get going", "vo/canals/boxcar_go_nag02.wav", true)
AddEmote("he'll help you if you let him", "vo/canals/boxcar_lethimhelp.wav", true)
AddEmote("we're just a lookout for the underground railroad", "vo/canals/boxcar_lookout.wav", true)
AddEmote("main station's right around the corner", "vo/canals/boxcar_lookout_b.wav", true)
AddEmote("they'll get you started on the right foot", "vo/canals/boxcar_lookout_d.wav", true)
AddEmote("guess those sirens are for you", "vo/canals/boxcar_sirens.wav", true)
AddEmote("come on in i'll show you what you're up against", "vo/canals/gunboat_comein.wav", true)
AddEmote("i think he's just finishing up now", "vo/canals/gunboat_finishingup.wav", true)
AddEmote("come on get in here", "vo/canals/gunboat_getin.wav", true)
AddEmote("here take a look at this", "vo/canals/gunboat_herelook.wav", true)
AddEmote("be glad you're not the guy they're looking for", "vo/canals/matt_beglad.wav", true)
AddEmote("poor bastard doesn't stand a chance", "vo/canals/matt_beglad_b.wav", true)
AddEmote("sounds like they're calling in every cp unit in city 17", "vo/canals/matt_beglad_c.wav", true)
AddEmote("that was a close call thanks for your help", "vo/canals/matt_closecall.wav", true)
AddEmote("now they're flooding the areas up ahead with manhacks", "vo/canals/matt_flood.wav", true)
AddEmote("you'd better get going before they sweep through here", "vo/canals/matt_flood_b.wav", true)
AddEmote("you'd better get going now", "vo/canals/matt_go_nag01.wav", true)
AddEmote("thanks but i'll be ok", "vo/canals/matt_go_nag02.wav", true)
AddEmote("i've got to stay and help any stragglers", "vo/canals/matt_go_nag03.wav", true)
AddEmote("you go on", "vo/canals/matt_go_nag05.wav", true)
AddEmote("good luck out there", "vo/canals/matt_goodluck.wav", true)
AddEmote("civil protection is on to us", "vo/canals/matt_tearinguprr.wav", true)
AddEmote("we're tearing up the railroad covering our tracks", "vo/canals/matt_tearinguprr_a.wav", true)
AddEmote("looks like you're gonna be the last one through", "vo/canals/matt_tearinguprr_b.wav", true)
AddEmote("thanks for the help but you better get outta here", "vo/canals/matt_thanksbut.wav", true)
AddEmote("oh shit too late", "vo/canals/matt_toolate.wav", true)
AddEmote("you got here at a bad time", "vo/canals/shanty_badtime.wav", true)
AddEmote("we got some ammo in those crates over there", "vo/canals/shanty_gotsomeammo.wav", true)
AddEmote("we got word you were coming", "vo/canals/shanty_gotword.wav", true)
AddEmote("help yourself to supplies and keep moving", "vo/canals/shanty_helpyourself.wav", true)
AddEmote("did you realize your contract was open to the highest bidder?", "vo/Citadel/br_bidder_b.wav", true)
AddEmote("that's all up to you my old friend", "vo/Citadel/br_gift_a.wav", true)
AddEmote("will you give your child a chance her mother never had?", "vo/Citadel/br_gift_c.wav", true)
AddEmote("what's this oh put it over there", "vo/Citadel/br_gravgun.wav", true)
AddEmote("guards get in here", "vo/Citadel/br_guards.wav", true)
AddEmote("you have my gratitude doctor", "vo/Citadel/br_guest_b.wav", true)
AddEmote("and then you deliver yourself?", "vo/Citadel/br_guest_d.wav", true)
AddEmote("i don't know what you can possibly hope to achieve", "vo/Citadel/br_mock05.wav", true)
AddEmote("i warned you this was futile", "vo/Citadel/br_mock06.wav", true)
AddEmote("i hope you said your farewells", "vo/Citadel/br_mock09.wav", true)
AddEmote("if only you had harnessed your boundless energy for a useful purpose", "vo/Citadel/br_mock13.wav", true)
AddEmote("i agree it's a total waste", "vo/Citadel/br_newleader_a.wav", true)
AddEmote("this one has proven to be a fine pawn", "vo/Citadel/br_newleader_c.wav", true)
AddEmote("i understand if you don't wish to discuss this in front of your friends", "vo/Citadel/br_nothingtosay_a.wav", true)
AddEmote("i'll send them on their way and then we can talk openly", "vo/Citadel/br_nothingtosay_b.wav", true)
AddEmote("impossible to describe with our limited vocabulary", "vo/Citadel/br_oheli09.wav", true)
AddEmote("oh shit", "vo/Citadel/br_ohshit.wav", true)
AddEmote("if you won't do the right thing for the good of all people", "vo/Citadel/br_playgame_b.wav", true)
AddEmote("maybe you'll do it for one of them", "vo/Citadel/br_playgame_c.wav", true)
AddEmote("thanks to you we have everything we need in that regard", "vo/Citadel/br_rabble_a.wav", true)
AddEmote("you're more than qualified to finish his research yourself", "vo/Citadel/br_rabble_b.wav", true)
AddEmote("if that's what it takes", "vo/Citadel/br_whatittakes.wav", true)
AddEmote("you need me", "vo/Citadel/br_youneedme.wav", true)
AddEmote("don't struggle honey", "vo/Citadel/eli_dontstruggle.wav", true)
AddEmote("don't worry about me", "vo/Citadel/eli_dontworryboutme.wav", true)
AddEmote("that's my girl", "vo/Citadel/eli_mygirl.wav", true)
AddEmote("save them for what", "vo/Citadel/eli_save.wav", true)
AddEmote("is it really that time again?", "vo/Citadel/gman_exit02.wav", true)
AddEmote("i'm really not at liberty to say", "vo/Citadel/gman_exit08.wav", true)
AddEmote("in the meantime", "vo/Citadel/gman_exit09.wav", true)
AddEmote("this is where i get off", "vo/Citadel/gman_exit10.wav", true)
AddEmote("they're looking for your car", "vo/coast/barn/male01/chatter.wav", true)
AddEmote("here come the dropships", "vo/coast/barn/male01/crapships.wav", true)
AddEmote("right along there and watch your step", "vo/coast/barn/male01/exit_watchstep.wav", true)
AddEmote("get your car in the barn", "vo/coast/barn/male01/getcarinbarn.wav", true)
AddEmote("get your car in the garage", "vo/coast/barn/male01/getcaringarage.wav", true)
AddEmote("get off the road", "vo/coast/barn/male01/getoffroad01.wav", true)
AddEmote("incoming dropship", "vo/coast/barn/male01/incomingdropship.wav", true)
AddEmote("it's a gunship", "vo/coast/barn/male01/lite_gunship01.wav", true)
AddEmote("gunship", "vo/coast/barn/male01/lite_gunship02.wav", true)
AddEmote("park it there", "vo/coast/barn/male01/parkit.wav", true)
AddEmote("you made it", "vo/coast/barn/male01/youmadeit.wav", true)
AddEmote("you idiot walking on the sand brings antlions after you", "vo/coast/bugbait/sandy_youidiot.wav", true)
AddEmote("you there", "vo/coast/bugbait/sandy_youthere.wav", true)
AddEmote("stop where you are stay on the rocks", "vo/coast/bugbait/sandy_stop.wav", true)
AddEmote("no! help!", "vo/coast/bugbait/sandy_help.wav", true)
AddEmote("yeah good idea hold on a sec", "vo/coast/cardock/le_goodidea.wav", true)
AddEmote("patch him up and get him to the back as soon as he's stable", "vo/coast/cardock/le_patchhim.wav", true)
AddEmote("i'll radio ahead to let the next base know you're coming", "vo/coast/cardock/le_radio.wav", true)
AddEmote("who's hurt?", "vo/coast/cardock/le_whohurt.wav", true)
AddEmote("well that's that", "vo/coast/odessa/nlo_cub_thatsthat.wav", true)
AddEmote("i couldn't have asked for a finer volunteer", "vo/coast/odessa/nlo_cub_volunteer.wav", true)
AddEmote("you'll make it through if anyone can", "vo/coast/odessa/nlo_cub_youllmakeit.wav", true)
AddEmote("good to know you", "vo/eli_lab/airlock_cit01.wav", true)
AddEmote("you'd better get going", "vo/eli_lab/airlock_cit02.wav", true)
AddEmote("awesome!", "vo/eli_lab/al_awesome.wav", true)
AddEmote("alright good you keep right on it", "vo/eli_lab/eli_goodvort.wav", true)
AddEmote("ughghgh", "vo/eli_lab/eli_handle_b.wav", true)
AddEmote("ughhh", "vo/k_lab/ba_thingaway02.wav", true)
AddEmote("feel free to look around", "vo/eli_lab/eli_lookaround.wav", true)
AddEmote("dr. breen", "vo/eli_lab/eli_vilebiz01.wav", true)
AddEmote("i can't look", "vo/k_lab/ba_cantlook.wav", true)
AddEmote("careful", "vo/k_lab/ba_careful01.wav")
AddEmote("be careful!", "vo/k_lab/ba_careful01.wav", true)
AddEmote("forget about that thing", "vo/k_lab/ba_forgetthatthing.wav", true)
AddEmote("get it off me", "vo/k_lab/ba_getitoff02.wav", true)
AddEmote("get down outta sight", "vo/k_lab/ba_getoutofsight01.wav", true)
AddEmote("i'll come find you", "vo/k_lab/ba_getoutofsight02.wav", true)
AddEmote("guh", "vo/k_lab/ba_guh.wav", true)
AddEmote("hey hey he's back", "vo/k_lab/ba_hesback01.wav", true)
AddEmote("i'm getting him outta there", "vo/k_lab/ba_hesback02.wav", true)
AddEmote("well is he here?", "vo/k_lab/ba_ishehere.wav", true)
AddEmote("you mean it's working?", "vo/k_lab/ba_itsworking01.wav", true)
AddEmote("for real this time?", "vo/k_lab/ba_itsworking02.wav", true)
AddEmote("i still have nightmares about that cat", "vo/k_lab/ba_itsworking04.wav", true)
AddEmote("i've gotta get back on my shift", "vo/k_lab/ba_myshift01.wav", true)
AddEmote("but ok", "vo/k_lab/ba_myshift02.wav")
AddEmote("yeah longer if we're lucky", "vo/k_lab/ba_longer.wav", true)
AddEmote("and not a moment too soon", "vo/k_lab/ba_nottoosoon01.wav", true)
AddEmote("that's what you said last time", "vo/k_lab/ba_saidlasttime.wav", true)
AddEmote("i can see your mit education really pays for itself", "vo/k_lab/ba_sarcastic03.wav", true)
AddEmote("i thought you got rid of that pest", "vo/k_lab/ba_thatpest.wav", true)
AddEmote("there he is", "vo/k_lab/ba_thereheis.wav", true)
AddEmote("there you are", "vo/k_lab/ba_thereyouare.wav", true)
AddEmote("here we go", "vo/k_lab/ba_thingaway01.wav", true)
AddEmote("get that thing away from me", "vo/k_lab/ba_thingaway03.wav", true)
AddEmote("what's the meaning of this?", "vo/k_lab/br_tele_02.wav", true)
AddEmote("who are you?", "vo/k_lab/br_tele_03.wav")
AddEmote("how did you get in here?", "vo/k_lab/br_tele_05.wav", true)
AddEmote("see for yourself", "vo/k_lab/eli_seeforyourself.wav", true)
AddEmote("shut it down shut it down", "vo/k_lab/eli_shutdown.wav", true)
AddEmote("ahhhh", "vo/k_lab/kl_ahhhh.wav", true)
AddEmote("there's a charger on the wall", "vo/k_lab/kl_charger01.wav", true)
AddEmote("dear me", "vo/k_lab/kl_dearme.wav", true)
AddEmote("well did it work?", "vo/k_lab/kl_diditwork.wav", true)
AddEmote("excellent!", "vo/k_lab/kl_excellent.wav", true)
AddEmote("right you are", "vo/k_lab/kl_fewmoments01.wav", true)
AddEmote("speak to you again in a few moments", "vo/k_lab/kl_fewmoments02.wav", true)
AddEmote("oh fiddlesticks what now", "vo/k_lab/kl_fiddlesticks.wav", true)
AddEmote("final sequence", "vo/k_lab/kl_finalsequence02.wav", true)
AddEmote("you must get out of here", "vo/k_lab/kl_getoutrun02.wav", true)
AddEmote("run!", "vo/k_lab/kl_getoutrun03.wav", true)
AddEmote("here my pet", "vo/k_lab/kl_heremypet01.wav", true)
AddEmote("no not up there", "vo/k_lab/kl_heremypet02.wav", true)
AddEmote("interference!", "vo/k_lab/kl_interference.wav", true)
AddEmote("lamarr", "vo/k_lab/kl_hedyno01.wav", true)
AddEmote("heady", "vo/k_lab/kl_hedyno02.wav", true)
AddEmote("is lamarr with him?", "vo/k_lab/kl_islamarr.wav", true)
AddEmote("lamarr there you are", "vo/k_lab/kl_lamarr.wav", true)
AddEmote("careful lamarr those are quite fragile", "vo/k_lab/kl_nocareful.wav", true)
AddEmote("conditions could hardly be more ideal", "vo/k_lab/kl_moduli02.wav", true)
AddEmote("my goodness", "vo/k_lab/kl_mygoodness01.wav", true)
AddEmote("it really is you isn't it?", "vo/k_lab/kl_mygoodness03.wav", true)
AddEmote("your talents surpass your loveliness", "vo/k_lab/kl_nonsense.wav", true)
AddEmote("oh dear", "vo/k_lab/kl_ohdear.wav", true)
AddEmote("indeed it is", "vo/k_lab/kl_packing01.wav", true)
AddEmote("slip in to your suit now", "vo/k_lab/kl_slipin02.wav", true)
AddEmote("i'm eager to see if your old suit still fits", "vo/k_lab/kl_suitfits02.wav", true)
AddEmote("then where is he?", "vo/k_lab/kl_thenwhere.wav", true)
AddEmote("what is it?", "vo/k_lab/kl_whatisit.wav", true)
AddEmote("i wish i knew!", "vo/k_lab/kl_wishiknew.wav", true)
AddEmote("go on get going", "vo/k_lab2/ba_getgoing.wav", true)
AddEmote("well man that's good news", "vo/k_lab2/ba_goodnews.wav", true)
AddEmote("i almost gave you guys up for lost", "vo/k_lab2/ba_goodnews_b.wav", true)
AddEmote("i'll take all the help i can get", "vo/k_lab2/ba_goodnews_c.wav", true)
AddEmote("aw crap incoming!", "vo/k_lab2/ba_incoming.wav", true)
AddEmote("so there you see?", "vo/k_lab2/kl_notallhopeless.wav", true)
AddEmote("it's not all hopeless", "vo/k_lab2/kl_notallhopeless_b.wav", true)
AddEmote("there's only one heady", "vo/k_lab2/kl_onehedy.wav", true)
AddEmote("fascinating!", "vo/k_lab2/kl_slowteleport01.wav", true)
AddEmote("aim for the head", "vo/ravenholm/aimforhead.wav", true)
AddEmote("guard yourself well", "vo/ravenholm/bucket_guardwell.wav", true)
AddEmote("there you are at last", "vo/ravenholm/bucket_thereyouare.wav", true)
AddEmote("better than better", "vo/ravenholm/cartrap_better.wav", true)
AddEmote("yes come to me come", "vo/ravenholm/engage01.wav", true)
AddEmote("come!", {"vo/ravenholm/engage02.wav", "vo/ravenholm/engage03.wav"}, true)
AddEmote("i will end your torment", "vo/ravenholm/engage04.wav", true)
AddEmote("let me end your torment", "vo/ravenholm/engage05.wav", true)
AddEmote("yes my children it is i", "vo/ravenholm/engage06.wav", true)
AddEmote("come to the light i carry come", "vo/ravenholm/engage07.wav", true)
AddEmote("it is not me you want but the light that shines through me", "vo/ravenholm/engage08.wav", true)
AddEmote("come to the light", "vo/ravenholm/engage09.wav", true)
AddEmote("go quickly", "vo/ravenholm/exit_goquickly.wav", true)
AddEmote("hurry while i hold the gate", "vo/ravenholm/exit_hurry.wav", true)
AddEmote("flee brother", "vo/ravenholm/exit_nag01.wav", true)
AddEmote("onward to the mines", "vo/ravenholm/exit_nag02.wav", true)
AddEmote("look out brother behind you", "vo/ravenholm/firetrap_lookout.wav", true)
AddEmote("well done brother", "vo/ravenholm/firetrap_welldone.wav", true)
AddEmote("stay close to me brother", "vo/ravenholm/grave_stayclose.wav", true)
AddEmote("out of my way", "vo/ravenholm/monk_blocked01.wav", true)
AddEmote("look out", "vo/ravenholm/monk_blocked02.wav")
AddEmote("stand aside brother", "vo/ravenholm/monk_blocked03.wav", true)
AddEmote("cover me brother", "vo/ravenholm/monk_coverme01.wav", true)
AddEmote("your assistance brother", "vo/ravenholm/monk_coverme02.wav", true)
AddEmote("over here brother", "vo/ravenholm/monk_coverme03.wav", true)
AddEmote("to me brother", "vo/ravenholm/monk_coverme04.wav", true)
AddEmote("i require your assistance brother", "vo/ravenholm/monk_coverme05.wav", true)
AddEmote("where art thou brother", "vo/ravenholm/monk_coverme07.wav", true)
AddEmote("beware!", "vo/ravenholm/monk_danger02.wav", true)
AddEmote("careful brother", "vo/ravenholm/monk_danger03.wav", true)
AddEmote("i am outnumbered", "vo/ravenholm/monk_helpme01.wav", true)
AddEmote("help me brother", "vo/ravenholm/monk_helpme02.wav", true)
AddEmote("i cannot fight them all alone", "vo/ravenholm/monk_helpme03.wav", true)
AddEmote("lend a hand brother", "vo/ravenholm/monk_helpme04.wav", true)
AddEmote("i need help brother", "vo/ravenholm/monk_helpme05.wav", true)
AddEmote("rest my child", "vo/ravenholm/monk_kill03.wav", true)
AddEmote("i think no worse of thee", "vo/ravenholm/monk_kill04.wav", true)
AddEmote("may the light of lights be with you", "vo/ravenholm/monk_kill05.wav", true)
AddEmote("you meant no harm", "vo/ravenholm/monk_kill06.wav", true)
AddEmote("be free my child", "vo/ravenholm/monk_kill09.wav", true)
AddEmote("the grave holds nothing worse for you", "vo/ravenholm/monk_kill10.wav", true)
AddEmote("i remember your true face", "vo/ravenholm/monk_kill11.wav", true)
AddEmote("so again i am alone", "vo/ravenholm/monk_mourn03.wav", true)
AddEmote("my advice to you is aim for the head", "vo/ravenholm/shotgun_advice.wav", true)
AddEmote("here i have a more suitable gun for you", "vo/ravenholm/shotgun_bettergun.wav", true)
AddEmote("catch!", "vo/ravenholm/shotgun_catch.wav", true)
AddEmote("come closer", "vo/ravenholm/shotgun_closer.wav", true)
AddEmote("hush", "vo/ravenholm/shotgun_hush.wav")
AddEmote("good now keep it close", "vo/ravenholm/shotgun_keepitclose.wav", true)
AddEmote("they come", "vo/ravenholm/shotgun_theycome.wav", true)
AddEmote("if you can hold them off i'm almost done here", "vo/Streetwar/tunnel/male01/c17_06_det02.wav", true)
AddEmote("stand back it's gonna blow", "vo/Streetwar/tunnel/male01/c17_06_det04.wav", true)
AddEmote("hey it's me open the door", "vo/Streetwar/tunnel/male01/c17_06_password01.wav", true)
AddEmote("what's the password?", "vo/Streetwar/tunnel/male01/c17_06_password02.wav", true)
AddEmote("password!", "vo/Streetwar/tunnel/male01/c17_06_password03.wav", true)
AddEmote("come on in", "vo/Streetwar/tunnel/male01/c17_06_password04.wav", true)
AddEmote("ok come across", "vo/Streetwar/tunnel/male01/c17_06_plank01.wav", true)
AddEmote("that damn thing haunts me", "vo/Streetwar/sniper/ba_hauntsme.wav", true)
AddEmote("did you hear a cat just now?", "vo/Streetwar/sniper/ba_hearcat.wav", true)
AddEmote("hey come on", "vo/Streetwar/sniper/ba_heycomeon.wav", true)
AddEmote("let's get going", "vo/Streetwar/sniper/ba_letsgetgoing.wav", true)
AddEmote("heeelp", "vo/Streetwar/sniper/male01/c17_09_help01.wav", true)
AddEmote("help me!", "vo/Streetwar/sniper/male01/c17_09_help02.wav", true)
AddEmote("is somebody up there?", "vo/Streetwar/sniper/male01/c17_09_help03.wav", true)
AddEmote("damnit all", "vo/Streetwar/rubble/ba_damnitall.wav", true)
AddEmote("hey help me out here", "vo/Streetwar/rubble/ba_helpmeout.wav", true)
AddEmote("well i'll be damned", "vo/Streetwar/rubble/ba_illbedamned.wav", true)
AddEmote("and if you see dr. breen tell him i said fuck you", "vo/Streetwar/rubble/ba_tellbreen.wav", true)
AddEmote("done!", "vo/Streetwar/nexus/ba_done.wav", true)
AddEmote("great i'll open this up", "vo/Streetwar/nexus/ba_illopenthis.wav", true)
AddEmote("so much for stealth we've been spotted", "vo/Streetwar/nexus/ba_spotted.wav", true)
AddEmote("we're surrounded", "vo/Streetwar/nexus/ba_surrounded.wav", true)
AddEmote("then let's go", "vo/Streetwar/nexus/ba_thenletsgo.wav", true)
AddEmote("uh oh dropships", "vo/Streetwar/nexus/ba_uhohdropships.wav", true)
AddEmote("hey let us outta here", "vo/Streetwar/nexus/male01/c17_10_letusout.wav", true)
AddEmote("let us thru!", "vo/Streetwar/barricade/male01/c17_05_letusthru.wav", true)
AddEmote("let us through!", "vo/Streetwar/barricade/male01/c17_05_letusthru.wav", true)
AddEmote("open the gate!", "vo/Streetwar/barricade/male01/c17_05_opengate.wav", true)
AddEmote("how dare you even mention her", "vo/Citadel/al_dienow_b.wav", true)
AddEmote("alyx my dear you have your mother's eyes but your father's stubborn nature", "vo/Citadel/br_stubborn.wav", true)
AddEmote("it isn't necessary", "vo/Citadel/mo_necessary.wav", true)
AddEmote("he's dead", {"vo/npc/male01/gordead_ques01.wav", "vo/npc/male01/gordead_ques07.wav"}, true)
AddEmote("oh my god it's freeman", {"vo/npc/male01/gordead_ques03a.wav", "vo/npc/male01/gordead_ques03b.wav"}, true)
AddEmote("now what?", "vo/npc/male01/gordead_ans01.wav")
AddEmote("oh god", "vo/npc/male01/gordead_ans04.wav")
AddEmote("we're done for", "vo/npc/male01/gordead_ans14.wav", true)
AddEmote("i'm ganna be sick", "vo/npc/male01/gordead_ans19.wav", true)
AddEmote("should we bury him here?", "vo/npc/male01/gordead_ans08.wav", true)
AddEmote("what's the use?", "vo/npc/male01/gordead_ans11.wav", true)
AddEmote("what's the point?", "vo/npc/male01/gordead_ans12.wav", true)
AddEmote("this is bad", "vo/npc/male01/gordead_ques10.wav", true)
AddEmote("and things were going so well", "vo/npc/male01/gordead_ans02.wav", true)
AddEmote("don't tell me", "vo/npc/male01/gordead_ans03.wav", true)
AddEmote("please no", "vo/npc/male01/gordead_ans06.wav")
AddEmote("if you dare say that's gotta hurt i'll kill you", "vo/npc/male01/gordead_ans07.wav", true)
AddEmote("i had a feeling even he couldn't help us", "vo/npc/male01/gordead_ans09.wav", true)
AddEmote("spread the word", "vo/npc/male01/gordead_ans10.wav", true)
AddEmote("why go on?", "vo/npc/male01/gordead_ans13.wav", true)
AddEmote("well, now what?", "vo/npc/male01/gordead_ans15.wav", true)
AddEmote("well now what?", "vo/npc/male01/gordead_ans15.wav", true)
AddEmote("dibs on the suit", "vo/npc/male01/gordead_ans16.wav", true)
AddEmote("wait a second that's not gordon freeman", "vo/npc/male01/gordead_ans17.wav", true)
AddEmote("he's done this before he'll be ok", "vo/npc/male01/gordead_ans18.wav", true)
AddEmote("somebody take his crowbar", "vo/npc/male01/gordead_ans20.wav", true)
AddEmote("what a way to go", "vo/npc/male01/gordead_ques02.wav", true)
AddEmote("freeman is dead?", "vo/npc/male01/gordead_ques04.wav", true)
AddEmote("that's not freeman is it?", "vo/npc/male01/gordead_ques05.wav", true)
AddEmote("this can't be", "vo/npc/male01/gordead_ques06.wav", true)
AddEmote("he came a long way from black mesa", "vo/npc/male01/gordead_ques08.wav", true)
AddEmote("i thought he was invincible", "vo/npc/male01/gordead_ques11.wav", true)
AddEmote("so much for doctor freeman", "vo/npc/male01/gordead_ques12.wav", true)
AddEmote("so much for our last hope", "vo/npc/male01/gordead_ques13.wav", true)
AddEmote("it's not supposed to end like this", "vo/npc/male01/gordead_ques14.wav", true)
AddEmote("dr. freeman can you hear me? do not go in to the light", "vo/npc/male01/gordead_ques15.wav", true)
AddEmote("what now?", "vo/npc/male01/gordead_ques16.wav")
AddEmote("any last words doc?", "vo/npc/male01/gordead_ques17.wav", true)
AddEmote("gotta reload", "vo/npc/male01/gottareload01.wav", true)
AddEmote("heads up", {"vo/npc/male01/headsup01.wav", "vo/npc/male01/headsup02.wav"}, true)
AddEmote("take this medkit", {"vo/npc/male01/health01.wav", "vo/npc/male01/health02.wav", "vo/npc/male01/health03.wav"}, true)
AddEmote("here have a medkit", "vo/npc/male01/health04.wav", true)
AddEmote("here patch yourself up", "vo/npc/male01/health05.wav", true)
AddEmote("hello dr. freeman", {"vo/npc/male01/hellodrfm01.wav", "vo/npc/male01/hellodrfm02.wav"}, true)
AddEmote("i've got my little corner and i'm sticking to it", "vo/npc/male01/littlecorner01.wav", true)
AddEmote("at ease loser", "speach/ael.ogg", true)
AddEmote("go!", "speach/go.ogg", true)
AddEmote("go go gal o sengen!", "speach/gogalo.ogg", true)
AddEmote("who's trying to sneak up on me?", "speach/wttsuom.ogg", true)
AddEmote("/taunt_04", "speach/taunt_04.ogg", true)
AddEmote("thanks", "speach/gabe_thanks.ogg")
AddEmote("worth the wait", "speach/gabe_wtw.ogg", true)
AddEmote("gaben", "speach/gabe_gaben.ogg", true)
AddEmote("oh and before i forget", "vo/trainyard/ba_crowbar01.wav", true)
AddEmote("what are we going to do?", "vo/trainyard/wife_whattodo.wav", true)
AddEmote("when is it all going to end?", "vo/trainyard/wife_end.wav", true)
AddEmote("i can't take it anymore", "vo/trainyard/wife_canttake.wav", true)
AddEmote("where are you taking me?", "vo/trainyard/man_whereyoutakingme.wav", true)
AddEmote("wait a minute", "vo/trainyard/man_whereyoutakingme.wav")
AddEmote("me?", "vo/trainyard/man_me.wav")
AddEmote("great scott", "vo/trainyard/kl_morewarn01.wav", true)
AddEmote("i expected more warning", "vo/trainyard/kl_morewarn03.wav", true)
AddEmote("it's all right", "vo/trainyard/husb_allright.wav")
AddEmote("don't worry", "vo/trainyard/husb_dontworry.wav")
AddEmote("everything's gonna be okay", "vo/trainyard/husb_okay.wav", true)
AddEmote("we'll think of something", "vo/trainyard/husb_think.wav", true)
AddEmote("don't drink the water", "vo/trainyard/cit_water.wav", true)
AddEmote("oh i thought you were a cop", "vo/trainyard/cit_window_cop.wav", true)
AddEmote("just this once i hope you're wrong", "vo/trainyard/cit_window_hope.wav", true)
AddEmote("look at em down there", "vo/trainyard/cit_window_look.wav", true)
AddEmote("he's one of us", "vo/trainyard/cit_window_stand.wav", true)
AddEmote("i told you they'd be coming for us next", "vo/trainyard/cit_window_usnext.wav", true)
AddEmote("i didn't see you get on", "vo/trainyard/cit_train_geton.wav", true)
AddEmote("well end of the line", "vo/trainyard/cit_train_endline.wav", true)
AddEmote("just be glad you don't live there", "vo/trainyard/cit_raid_use01.wav", true)
AddEmote("if you're looking for a place to stay you better keep going", "vo/trainyard/cit_raid_use02.wav", true)
AddEmote("they have no reason to come to our place", "vo/trainyard/cit_raid_reason.wav", true)
AddEmote("don't worry they'll find one", "vo/trainyard/cit_raid_findone.wav", true)
AddEmote("*ranting*", "vo/trainyard/cit_pacing.wav", true)
AddEmote("i'm working up the nerve to go on", "vo/trainyard/cit_nerve.wav", true)
AddEmote("all right i'm moving jeez", "vo/trainyard/cit_lug_allright.wav", true)
AddEmote("but this stuff it's all i have left", "vo/trainyard/cit_lug_allihave.wav", true)
AddEmote("psst hey you in here", "vo/trainyard/cit_hall_psst.wav", true)
AddEmote("head for the roof there's no time to lose", "vo/trainyard/cit_hall_roof.wav", true)
AddEmote("was that you knocking? i didn't even know we still had a door", "vo/trainyard/cit_drunk.wav", true)
AddEmote("keep moving head for the roof", "vo/trainyard/cit_blocker_roof.wav", true)
AddEmote("go on i'll hold them", "vo/trainyard/cit_blocker_holdem.wav", true)
AddEmote("get in here quick", "vo/trainyard/cit_blocker_getin.wav", true)
AddEmote("i'm thinking i'm thinking", "vo/trainyard/ba_thinking01.wav", true)
AddEmote("yeah you and me both doc", "vo/trainyard/ba_tellme01.wav", true)
AddEmote("hey sorry for the scare i had to put on a show for the cameras", "vo/trainyard/ba_sorryscare.wav", true)
AddEmote("i'll meet up with you later", "vo/trainyard/ba_meetyoulater01.wav", true)
AddEmote("sorry doc but look who's here", "vo/trainyard/ba_lookwho.wav", true)
AddEmote("good luck out there buddy", "vo/trainyard/ba_goodluck01.wav", true)
AddEmote("you're gonna need it", "vo/trainyard/ba_goodluck02.wav", true)
AddEmote("they're right outside get going", "vo/trainyard/ba_exitnag03.wav", true)
AddEmote("will you get going?", "vo/trainyard/ba_exitnag04.wav", true)
AddEmote("move it along", "vo/trainyard/ba_exitnag05.wav", true)
AddEmote("stay back you'll attract unwanted attention", "vo/trainyard/male01/cit_bench01.wav", true)
AddEmote("i can't be seen talking to you not out here", "vo/trainyard/male01/cit_bench02.wav", true)
AddEmote("don't sit near me it'll look suspicious", "vo/trainyard/male01/cit_bench03.wav", true)
AddEmote("you're scaring off the pigeons", "vo/trainyard/male01/cit_bench04.wav", true)
AddEmote("the line starts at the end", "vo/trainyard/male01/cit_foodline01.wav", true)
AddEmote("you'll have to wait your turn like everybody else", "vo/trainyard/male01/cit_foodline02.wav", true)
AddEmote("you gotta be damn hungry to wait in line for this crap", "vo/trainyard/male01/cit_foodline03.wav", true)
AddEmote("cut it out", "vo/trainyard/male01/cit_hit01.wav")
AddEmote("stop that", "vo/trainyard/male01/cit_hit02.wav")
AddEmote("watch it will ya?", "vo/trainyard/male01/cit_hit03.wav", true)
AddEmote("no more", "vo/trainyard/male01/cit_hit04.wav")
AddEmote("that's enough of that", "vo/trainyard/male01/cit_hit05.wav")
AddEmote("new in town aren't ya?", "vo/trainyard/male01/cit_pedestrian01.wav", true)
AddEmote("word to the wise keep it to yourself", "vo/trainyard/male01/cit_pedestrian02.wav", true)
AddEmote("if i talk to you out here we'll both be in trouble", "vo/trainyard/male01/cit_pedestrian03.wav", true)
AddEmote("we can't be seen talking to each other", "vo/trainyard/male01/cit_pedestrian04.wav", true)
AddEmote("i'd like to help you but it's out of the question", "vo/trainyard/male01/cit_pedestrian05.wav", true)
AddEmote("this is my third transfer this year", "vo/trainyard/male01/cit_term_ques02.wav", true)
AddEmote("oh no now we're really gonna get it", "vo/trainyard/male01/cit_tvbust05.wav", true)
AddEmote("this doesn't look good", "vo/trainyard/male01/cit_window_use01.wav", true)
AddEmote("they're definitely coming in here", "vo/trainyard/male01/cit_window_use02.wav", true)
AddEmote("it was just a matter of time", "vo/trainyard/male01/cit_window_use03.wav", true)
AddEmote("here goes the rest of the neighborhood", "vo/trainyard/male01/cit_window_use04.wav", true)
AddEmote("stop we didn't do anything", "vo/canals/arrest_stop.wav", true)
AddEmote("gladly we accompany", "vo/npc/vortigaunt/accompany.wav", true)
AddEmote("we have lost all dear to us", "vo/npc/vortigaunt/alldear.wav", true)
AddEmote("as you wish", "vo/npc/vortigaunt/asyouwish.wav")
AddEmote("this body is yours to command", "vo/npc/vortigaunt/bodyyours.wav", true)
AddEmote("certainly", "vo/npc/vortigaunt/certainly.wav", true)
AddEmote("empower us", "vo/npc/vortigaunt/empowerus.wav", true)
AddEmote("we fear we have failed you", "vo/npc/vortigaunt/fearfailed.wav", true)
AddEmote("for freedom", "vo/npc/vortigaunt/forfreedom.wav", true)
AddEmote("gladly", "vo/npc/vortigaunt/gladly.wav")
AddEmote("here we stay", "vo/npc/vortigaunt/herewestay.wav", true)
AddEmote("our cause seems hopeless", "vo/npc/vortigaunt/hopeless.wav", true)
AddEmote("with pleasure", "vo/npc/vortigaunt/pleasure.wav", true)
AddEmote("satisfaction", "vo/npc/vortigaunt/satisfaction.wav", true)
AddEmote("we have survived worse across the ages", "vo/npc/vortigaunt/seenworse.wav", true)
AddEmote("stand clear", "vo/npc/vortigaunt/standclear.wav")
AddEmote("don't rely on it", "vo/npc/vortigaunt/vanswer08.wav", true)
AddEmote("where to now? and to what end?", "vo/npc/vortigaunt/whereto.wav", true)
AddEmote("yesss", "vo/npc/vortigaunt/yes.wav", true)
AddEmote("get outta there it's gonna blow", "radio/blow.wav", true)
AddEmote("bomb has been defused", "radio/bombdef.wav", true)
AddEmote("bomb has been planted", "radio/bombpl.wav", true)
AddEmote("sector clear", "radio/clear.wav", true)
AddEmote("get in position and wait for my go", "radio/com_getinpos.wav", true)
AddEmote("report in team", "radio/com_go.wav", true)
AddEmote("affirmative", "radio/ct_affirm.wav", true)
AddEmote("cover me", "radio/ct_coverme.wav", true)
AddEmote("enemy spotted", "radio/ct_enemys.wav", true)
AddEmote("fire in the hole", "radio/ct_fireinhole.wav", true)
AddEmote("i'm in position", "radio/ct_inpos.wav", true)
AddEmote("reporting in", "radio/ct_reportingin.wav", true)
AddEmote("counter-terrorists win", "radio/ctwin.wav", true)
AddEmote("enemy down", "radio/enemydown.wav", true)
AddEmote("team fall back", "radio/fallback.wav", true)
AddEmote("taking fire need assistance", "radio/fireassis.wav", true)
AddEmote("follow me!", "radio/followme.wav", true)
AddEmote("okay let's go", "radio/go.wav", true)
AddEmote("hostage down", "radio/hosdown.wav", true)
AddEmote("lock n' load", "radio/locknload.wav", true)
AddEmote("alright let's move out", "radio/moveout.wav", true)
AddEmote("negative", "radio/negative.wav", true)
AddEmote("hold this position", "radio/position.wav", true)
AddEmote("regroup team", "radio/regroup.wav", true)
AddEmote("roger that", "radio/roger.wav", true)
AddEmote("stick together team", "radio/sticktog.wav", true)
AddEmote("storm the front", "radio/stormfront.wav", true)
AddEmote("you take the point", "radio/takepoint.wav", true)
AddEmote("terrorists win", "radio/terwin.wav", true)
AddEmote("protect the vip team", "radio/vip.wav", true)
AddEmote("you're too slow", "speach/sanic4.ogg", true)
AddEmote("come on step it up", "speach/sanic3.ogg", true)
AddEmote("too easy piece of cake", "speach/sanic2.ogg", true)
AddEmote("sonic's the name speed's my game", "speach/sanic1.ogg", true)
AddEmote("give me the butter", "speach/givemethebutter.ogg", true)
AddEmote("you broke my grill?", "speach/youbrokemygrill.ogg", true)
AddEmote("oldest trick in the book", "speach/oldesttrickinthebook.ogg", true)
AddEmote("no i don't want that", "speach/noidontwantthat.ogg", true)
AddEmote("everyday's great at your junes", "speach/greatatyourjunes.ogg", true)
AddEmote("vgta", "speach/awthatstoobad.ogg", true)
AddEmote("*honk*", "speach/bikehorn.ogg", true)
AddEmote("gank!", "speach/gank.ogg", true)
AddEmote("i'm the coolest", "speach/imthecoolest.ogg", true)
AddEmote("vgtg", "speach/imthegreatest.ogg", true)
AddEmote("vgs", "speach/shazbot.ogg", true)
AddEmote("luigi i'm home", "speach/luigiimhome.ogg", true)
AddEmote("smoked your butt", "speach/smokedyourbutt.ogg", true)
AddEmote("how's it feel to burn?", "speach/feeltoburn.ogg", true)
AddEmote("farquadd", "speach/male_farquadd.ogg", true)
AddEmote("you bastards!", "speach/youbastards.ogg", true)
AddEmote("kill them all!", "speach/killthemall.ogg", true)
AddEmote("less talking more raiding", "speach/lesstalkmoreraid.ogg", true)
AddEmote("i will drink from your skull", "speach/drinkfromyourskull.ogg", true)
AddEmote("i'm gonna break your legs nice and slow", "speach/breakyourlegs.ogg", true)
AddEmote("it's almost harvesting season", "speach/almostharvestingseason.ogg", true)
AddEmote("thanksgiving blowout", "speach/thanksgivingblowout.ogg", true)
AddEmote("easy cheesey baked potato", "speach/cheesybakedpotato.ogg", true)

AddEmote("*spit*", "vo/Citadel/al_dienow.wav", true)
AddEmote("i've lost control of my life", "speach/dynamic/lost_control.ogg", true, nil, 0.85)
AddEmote("making chocolate pudding", "speach/dynamic/pudding.ogg", true, nil, 0.85)
AddEmote("order sent", "speach/dynamic/order_sent.ogg", true, nil, 0.85)

AddEmote("mado's nyan", "speach/dynamic/mados_nyan.ogg", true, nil, 0.85)
AddEmote("oh my god", "speach/dynamic/oh_my_god.ogg", true, nil, 0.85)
AddEmote("tuturuu", "speach/dynamic/tuturuu.ogg", true, nil, 0.85)
AddEmote("you don't scare me at all", "speach/dynamic/you_dont_scare_me_at_all.ogg", true, nil, 0.85)
AddEmote("ooh banana", "speach/dynamic/ooh_banana.ogg", true, nil, 0.85)
AddEmote("on the bed?", "speach/dynamic/wwawgdotb.ogg", true, nil, 0.85)
AddEmote("we'll be fine you just have to go", "speach/dynamic/wbfyjhtg.ogg", true, nil, 0.85)
AddEmote("this is my boomstick!", "speach/dynamic/this_is_my_boomstick.ogg", true, nil, 0.85)
AddEmote("pomf", "speach/dynamic/pomf.ogg", true, nil, 0.85)
AddEmote("yeah science", "speach/dynamic/yeah_science.ogg", true, nil, 0.85)
AddEmote("owooo", "speach/dynamic/owooo.ogg", true, nil, 0.85)
AddEmote("i feel good", "speach/dynamic/i_feel_good.ogg", true, nil, 0.85)
AddEmote("you're all a bunch of fucking idiots", "speach/dynamic/yaabofi.ogg", true, nil, 0.85)
AddEmote("timotei", "speach/dynamic/timotei.ogg", true, nil, 0.85)
AddEmote("sending out an sos", "speach/dynamic/sending_out_an_sos.ogg", true, nil, 0.85)
AddEmote("kakarot!", "speach/dynamic/kakarot.ogg", true, nil, 0.85)
AddEmote("gatorade", "speach/dynamic/gatorade.ogg", true, nil, 0.85)
AddEmote("lady you've got darkness on the brain", "speach/dynamic/lygdotb.ogg", true, nil, 0.85)
AddEmote("pickup3", "speach/dynamic/i_said_pickup_the_can.ogg", true, nil, 0.85)
AddEmote("pickup2", "speach/dynamic/pick_up_the_can.ogg", true, nil, 0.85)
AddEmote("blow over", "speach/dynamic/blow_over.ogg", true, nil, 0.85)
AddEmote("out the road", "speach/dynamic/out_the_road.ogg", true, nil, 0.85)
AddEmote("ya dirty shite ya mickey", "speach/dynamic/ya_dirty_shite_ya_mickey.ogg", true, nil, 0.85)
AddEmote("sit on that", "speach/dynamic/sit_on_that.ogg", true, nil, 0.85)
AddEmote("i am the real boss", "speach/dynamic/i_am_the_real_boss.ogg", true, nil, 0.85)
AddEmote("pickup1", "speach/dynamic/pickup1.ogg", true, nil, 0.85)
AddEmote("vagina", "speach/dynamic/vagina.ogg", true, nil, 0.85)
AddEmote("*audience*", "speach/dynamic/audience.ogg", true, nil, 0.85)
AddEmote("ara ara", "speach/dynamic/ara_ara.ogg", true, nil, 0.85)
AddEmote("nippah", "speach/dynamic/nippah.ogg", true, nil, 0.85)
AddEmote("lick my balls", "speach/dynamic/lick_my_balls.ogg", true, nil, 0.85)
AddEmote("you didn't say the magic word", "speach/dynamic/ydstmw.ogg", true, nil, 0.85)
AddEmote("oh my god we're doomed", "speach/dynamic/ohmygodweredoomed.ogg", true, nil, 0.85)
AddEmote("i won!", "speach/dynamic/i_won.ogg", true, nil, 0.85)
AddEmote("this is illegal you know", "speach/dynamic/this_is_illegal_you_know.ogg", true, nil, 0.85)
AddEmote("go and kill", "speach/dynamic/go_and_kill.ogg", true, nil, 0.85)
AddEmote("the ultimate evil", "speach/dynamic/the_ultimate_evil.ogg", true, nil, 0.85)
AddEmote("outto", "speach/dynamic/outto.ogg", true, nil, 0.85)
AddEmote("you shall not pass!", "speach/dynamic/you_shall_not_pass.ogg", true, nil, 0.85)
AddEmote("i'll end you!", "speach/dynamic/ill_end_you.ogg", true, nil, 0.85)
AddEmote("leerooy", "speach/dynamic/leerooy.ogg", true, nil, 0.7)
AddEmote("do it!", "speach/dynamic/do_it.ogg", true, nil, 0.85)
AddEmote("nyanpassu", "speach/dynamic/nyanpassu.ogg", true, nil, 0.85)
AddEmote("boring around here", "speach/dynamic/boring_around_here.ogg", true, nil, 0.85)
AddEmote("it's yours my friend", "speach/dynamic/its_yours_my_friend.ogg", true, nil, 0.85)
AddEmote("real soon...", "speach/dynamic/real_soon.ogg", true, nil, 0.85)
AddEmote("faces of evil", "speach/dynamic/faces_of_evil.ogg", true, nil, 0.85)
AddEmote("buttfun", "speach/dynamic/buttfun.ogg", true, nil, 0.85)
AddEmote("marshjellow", "speach/dynamic/marshjellow.ogg", true, nil, 0.85)
AddEmote("youlose", "speach/dynamic/youlose.ogg", true, nil, 0.85)
AddEmote("no dear that's wrong", "speach/dynamic/no_dear_thats_wrong.ogg", true, nil, 0.85)
AddEmote("*hentai*", "speach/dynamic/hentai.ogg", true, nil, 0.85)
AddEmote("this is a pig stye", "speach/dynamic/this_is_a_pig_stye.ogg", true, nil, 0.85)
AddEmote("do you understand?!", "speach/dynamic/do_you_understand.ogg", true, nil, 0.85)
AddEmote("fuck_everything!", "speach/dynamic/fuck_everything.ogg", true, nil, 0.85)
AddEmote("alright mister what do you think you're doing?", "speach/dynamic/amwdytyd.ogg", true, nil, 0.85)
AddEmote("dallas?", "speach/dynamic/dallas.ogg", true, nil, 0.85)
AddEmote("sallad", "speach/dynamic/salad.ogg", true, nil, 0.85)
AddEmote("are you listening to me?!", "speach/dynamic/are_you_listening_to_me.ogg", true, nil, 0.85)
AddEmote("god-emperor takara", "speach/dynamic/god-emperor_takara.ogg", true, nil, 0.85)
AddEmote("a thousand of my brothers' dicks!", "speach/dynamic/1000_dicks.ogg", true, nil, 0.85)
AddEmote("poopy poop poop poopster poop", "speach/dynamic/ppppp.ogg", true, nil, 0.7)
AddEmote("hello my friend", "speach/dynamic/hello_my_friend.ogg", true, nil, 0.85)
AddEmote("i don't like this one bit", "speach/dynamic/i_dont_like_this.ogg", true, nil, 0.85)
AddEmote("unacceptable!", "speach/dynamic/unacceptable.ogg", true)
AddEmote("haha!", "speach/dynamic/haha.ogg", true)
AddEmote("oh no we're all doomed", "speach/dynamic/alldoomed.ogg", true)
AddEmote("you better get out!", "speach/dynamic/you_better_get_out.ogg", true)
AddEmote("what in blazes?!", "speach/dynamic/what_in_blazes.ogg", true)
AddEmote("i'm getting dizzay!", "speach/dynamic/im_getting_dizzay.ogg", true)
AddEmote("ohh too bad!", "speach/dynamic/ohh_too_bad.ogg", true)
AddEmote("whooo!", "speach/dynamic/whooo.ogg", true)
AddEmote("medic!", "speach/dynamic/medic.ogg", true)
AddEmote("saveme", "speach/dynamic/saveme.ogg", true)
AddEmote("the evil seed", "speach/dynamic/evil_seed.ogg", true)
AddEmote("gee it sure is boring around here", "speach/dynamic/it_sure_is_boring.ogg", true)
AddEmote("great i'll grab my stuff", "speach/dynamic/ill_grab_my_stuff.ogg", true)
AddEmote("zilmoan", "speach/dynamic/zilmoan.ogg", true)
AddEmote("alright!", "speach/dynamic/alright.ogg", true)
AddEmote("fantastic!", "speach/dynamic/fantastic.ogg", true)
AddEmote("get out of the way!", "speach/dynamic/get_out_of_the_way.ogg", true)
AddEmote("hey where are we?", "speach/dynamic/hey_where_are_we.ogg", true)
AddEmote("i wanna go home!", "speach/dynamic/i_wanna_go_home.ogg", true)
AddEmote("that's how dumb you sound", "speach/dynamic/thats_how_dumb_you_sound.ogg", true)
AddEmote("ahaha", "speach/dynamic/ahaha.ogg", true)
AddEmote("what's wrong? is that all you've got brother?", "speach/dynamic/wwitaygb.ogg", true)
AddEmote("what's that?!", "speach/dynamic/whats_that.ogg", true)
AddEmote("are you kidding me?!", "speach/dynamic/are_you_kidding_me.ogg", true)
AddEmote("called a target", "speach/dynamic/where_i_come_from_target.ogg", true)
AddEmote("show me your moves", "speach/dynamic/show_me_your_moves.ogg", true)
AddEmote("falcon death", "speach/dynamic/falcon_death.ogg", true)
AddEmote("naaa", "speach/dynamic/naaa.ogg", true)
AddEmote("baaarge", "speach/dynamic/baaarge.ogg", true)
AddEmote("subaluwa!", "speach/dynamic/subaluwa.ogg", true)
AddEmote("liquid's laugh", "speach/dynamic/liquids_laugh.ogg", true)
AddEmote("ocelot's laugh", "speach/dynamic/ocelots_laugh.ogg", true)
AddEmote("no problem...", "speach/dynamic/no_problem.ogg", true)
AddEmote("more more", "speach/dynamic/more_more.ogg", true)
AddEmote("eahhh", "speach/dynamic/eahhh.ogg", true)
AddEmote("w33d", "speach/dynamic/w33d.ogg", true)
AddEmote("you are a pirate", "speach/dynamic/you_are_a_pirate.ogg", true)
AddEmote("whatchasay", "speach/dynamic/watchasay.ogg", true)
AddEmote("to glory!", "speach/dynamic/to_glory.ogg", true)
AddEmote("chaaarge!", "speach/dynamic/chaaarge.ogg", true)
AddEmote("here they come lads!", "speach/dynamic/here_they_come_lads.ogg", true)
AddEmote("to me!", "speach/dynamic/to_me.ogg", true)
AddEmote("fuck you!", "speach/dynamic/fuck_you.ogg", true)
AddEmote("ladies first", "speach/dynamic/ladies_first.ogg", true)
AddEmote("tearapartlisa", "speach/dynamic/tearapartlisa.ogg", true)
AddEmote("bsheymarc", "speach/dynamic/bsheymarc.ogg", true)
AddEmote("keep up motherfucker", "speach/dynamic/keep_up_motherfucker.ogg", true)
AddEmote("nilbog", "speach/dynamic/nilbog.ogg", true)
AddEmote("watch yo profamity", "speach/dynamic/watch_yo_profamity.ogg", true)
AddEmote("nnbpd", "speach/dynamic/nnbpd.ogg", true)
AddEmote("iwishiwereabird", "speach/dynamic/iwishiwereabird.ogg", true)
AddEmote("everyone!", "speach/dynamic/everyone.ogg", true)
AddEmote("purupuru", "speach/dynamic/purupuru.ogg", true)
AddEmote("niconi", "speach/dynamic/niconi.ogg", true)
AddEmote("yarr harr", "speach/dynamic/yarr_harr.ogg", true)
AddEmote("just something i whipped up", "speach/dynamic/just_something_i_whipped_up.ogg", true)
AddEmote("medic!!", "speach/dynamic/medic2.ogg", true)
AddEmote("shesaid", "speach/dynamic/shesaid.ogg", true)
AddEmote("mattferrit", "speach/dynamic/mattferrit.ogg", true)
AddEmote("werd", "speach/dynamic/werd.ogg", true)
AddEmote("chortle", "speach/dynamic/chortle.ogg", true)
AddEmote("stfu", "speach/dynamic/stfu.ogg")
AddEmote("wtf are you doing?", "speach/dynamic/wtf_are_you_doing.ogg", true)
AddEmote("smd", "speach/dynamic/smd.ogg", true)
AddEmote("you better watch out", "speach/dynamic/you_better_watch_out.ogg", true)
AddEmote("i fucking hate you", "speach/dynamic/i_fucking_hate_you.ogg", true)
AddEmote("i am a wizard", "speach/dynamic/i_am_a_wizard.ogg", true)
AddEmote("of course!", "speach/dynamic/of_course.ogg", true)
AddEmote("get out of my sight", "speach/dynamic/get_out_of_my_sight.ogg", true)
AddEmote("crush you in to the wind", "speach/dynamic/crush_you_in_to_the_wind.ogg", true)
AddEmote("penis penis penis penis penis penis", "speach/dynamic/penisx6.ogg", true)
AddEmote("it's a valleyship", "speach/dynamic/its_a_valleyship.ogg", true)
AddEmote("cheeki breeki", "speach/dynamic/cheeki_breeki.ogg", true)
AddEmote("euheuhue", "speach/dynamic/euheuhue.ogg", true)
AddEmote("omedetou", "speach/dynamic/omedetou.ogg", true)
